name: Build and push the latest build to staging

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]


jobs:
  build_push_image:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push staging image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true
  
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        uses: Azure/setup-helm@v3.3
        with:
          version: v3.3.1
        
      - name: Login Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: mslearn-gh-pipelines-10402
          cluster-name: contoso-video
          admin: 'false'
          use-kubelogin: 'true'
          
      - name: Run helm deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }}
          

          
      
