name: Build and push the latest build to staging

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]


jobs:
  build_push_image:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push staging image
        uses: docker/build-push-action@v3.1.1
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .
          # List of tags
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true

